data_config:
  dataset_config:
    data_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/predictions/"
  dataloader_config:
    num_workers: 8
output_config:
  out_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/evaluations/"
models:
  - name: "cv"



