- data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/physicsBased/predictions/"
    dataloader_config:
      num_workers: 8
  output_config:
    out_path: "/home/manolotis/sandbox/robustness_benchmark/physicsBased/evaluations/"
  model:
    name: "cv"