data_config:
  dataset_config:
    data_path: "/home/manolotis/sandbox/scenario_based_evaluation/physicsBased/predictions/"
  dataloader_config:
    num_workers: 8
output_config:
  out_path: "/home/manolotis/sandbox/scenario_based_evaluation/physicsBased/evaluations/"
models:
  - name: "cv"
  - name: "cvx6"
  - name: "cvx20"



