data_config:
  dataset_config:
    data_path: "ABSOLUTE_PATH_TO_PREDICTIONS_FOLDER"
#   example data_path: "/home/robustness_benchmark/physicsBased/predictions/"
  dataloader_config:
    num_workers: 8
output_config:
  out_path: "ABSOLUTE_PATH_TO_EVALUATIONS_FOLDER"
# example out_path: "/home/robustness_benchmark/physicsBased/evaluations/"
models:
  - name: "cv"



