test:
  data_config:
    dataset_config:
      data_path: "/home/manolotis/sandbox/robustness_benchmark/lstmAutoencoder/data/prerendered/training/"
      n_shards: 1
      input_data: [ "xy", "v_xy", "valid" ]
    dataloader_config:
      batch_size: 42
      shuffle: True
      num_workers: 8
  output_config:
    visualize: False
    out_path: "/home/manolotis/sandbox/robustness_benchmark/physicsBased/predictions/"
    viz_path: "/home/manolotis/sandbox/robustness_benchmark/physicsBased/plots/predictions/"
model:
  name: "cv"
