test:
  data_config:
    dataset_config:
      data_path: "ABSOLUTE_PATH_TO_DATA"
      n_shards: 1
      input_data: [ "xy", "v_xy", "valid" ]
    dataloader_config:
      batch_size: 42
      shuffle: True
      num_workers: 8
  output_config:
    visualize: False
    out_path: "ABSOLUTE_PATH_TO_PREDICTIONS_FOLDER"
    viz_path: "/ABSOLUTE_PATH_TO_PREDICTIONS_PLOTS_FOLDER"
model:
  name: "cv"
  n_predictions: 1
